// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZS0tS8aNv19ehYwKsUvguVssRtpfR1cI',
    appId: '1:969560871033:web:2cd5b701e04138aa1044a8',
    messagingSenderId: '969560871033',
    projectId: 'flutterfirebase-e8f21',
    authDomain: 'flutterfirebase-e8f21.firebaseapp.com',
    storageBucket: 'flutterfirebase-e8f21.appspot.com',
    measurementId: 'G-BJEYRF3M3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXAXs7e-3tra4hSuk2Xvc0rHRWGaZqTBE',
    appId: '1:969560871033:android:0a64fb315fddbcb11044a8',
    messagingSenderId: '969560871033',
    projectId: 'flutterfirebase-e8f21',
    storageBucket: 'flutterfirebase-e8f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wSSjcLvJivQq2XhTeoSRUvrs7c8BK6s',
    appId: '1:969560871033:ios:7d9c14df4a12e45d1044a8',
    messagingSenderId: '969560871033',
    projectId: 'flutterfirebase-e8f21',
    storageBucket: 'flutterfirebase-e8f21.appspot.com',
    iosBundleId: 'com.example.firebaseAuthh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wSSjcLvJivQq2XhTeoSRUvrs7c8BK6s',
    appId: '1:969560871033:ios:7d9c14df4a12e45d1044a8',
    messagingSenderId: '969560871033',
    projectId: 'flutterfirebase-e8f21',
    storageBucket: 'flutterfirebase-e8f21.appspot.com',
    iosBundleId: 'com.example.firebaseAuthh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZS0tS8aNv19ehYwKsUvguVssRtpfR1cI',
    appId: '1:969560871033:web:69dc53a53f8030111044a8',
    messagingSenderId: '969560871033',
    projectId: 'flutterfirebase-e8f21',
    authDomain: 'flutterfirebase-e8f21.firebaseapp.com',
    storageBucket: 'flutterfirebase-e8f21.appspot.com',
    measurementId: 'G-VDLS1MK99D',
  );
}
